### ISSUE TITLE
ActivityTypes field missing in destination

### ISSUE THREAD

**Issue by lespaceman** [Kites-Foundation/hellomunnar-cms#11]
ActivityTypes field is required on the destination page.

**Comment by gautamkrishnar** [comment]
Why do we need ActivityTypes? It's not in the diagram. AFAIK that is what activity connections are for @lespaceman can you please elaborate?

![Screenshot 2021-09-16 at 8 03 52 PM](https://user-images.githubusercontent.com/8397274/133631893-321c2634-96e8-4e5b-8da0-5d9b37ca05b7.png)

**Comment by gautamkrishnar** [comment]
Destination's activity connections connects to activity types

**Comment by lespaceman** [comment]
@gautamkrishnar apologies for missing activity tags in the diagram. But it's there in the app already. We missed it while adding creating the diagram. Please check the screenshot. 

![Screenshot 2021-09-16 at 8 27 00 PM](https://user-images.githubusercontent.com/68752210/133635932-fb057150-8285-44ad-a3e5-9e54b535b5fe.png)

**Comment by gautamkrishnar** [comment]
@lespaceman fixed and deployed
