### ISSUE TITLE
Update Actvities.bookingUrl to a component type that supports the modal

### ISSUE THREAD

**Issue by gautamkrishnar** [Kites-Foundation/hellomunnar-cms#5]
![Screenshot 2021-03-17 at 4 46 59 PM](https://user-images.githubusercontent.com/8397274/111459342-9311b500-8740-11eb-9a80-37f647ef4782.png)

Create a component type named `booking` under singltype category and link it to Actvities.booking. To support the above modal data. Actvities.bookingUrl should be removed.

**Comment by akhilmhdh** [comment]
@gautamkrishnar Singletype always can have only one way relation. Also is the link constant.

**Comment by gautamkrishnar** [comment]
@akhilmhdh I meant to create component type not single type

**Comment by gautamkrishnar** [comment]
closed by #6
